#ifndef _ALPHAPI_ONE_S_CONFIG_H_
#define _ALPHAPI_ONE_S_CONFIG_H_

#include <driver/gpio.h>
#include <driver/uart.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_CODEC_UART_PORT UART_NUM_1
#define AUDIO_CODEC_UART_BAUD_RATE 460800
#define AUDIO_CODEC_UART_TX_PIN GPIO_NUM_3
#define AUDIO_CODEC_UART_RX_PIN GPIO_NUM_0

#define BUTTON_A_GPIO GPIO_NUM_13
#define BUTTON_B_GPIO GPIO_NUM_12
#define BUTTON_C_GPIO GPIO_NUM_11
#define BUTTON_D_GPIO GPIO_NUM_10

#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 160
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR false
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define DISPLAY_MOSI_PIN GPIO_NUM_38
#define DISPLAY_MISO_PIN GPIO_NUM_45
#define DISPLAY_CLK_PIN GPIO_NUM_37
#define DISPLAY_CS_PIN GPIO_NUM_34
#define DISPLAY_DC_PIN GPIO_NUM_36
#define DISPLAY_RESET_PIN GPIO_NUM_35
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_33
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#define DISPLAY_SPI_CLOCK_HZ (26 * 1000 * 1000)

#endif  // _ALPHAPI_ONE_S_CONFIG_H_
